set linesize 180 
set pagesize 50
set feedback off
col SID for 99999
col START_TIME for a19
col LAST_UPDATE_TIME for a19
col MESSAGE for a90

SELECT 
SID, 
TO_CHAR(START_TIME,'yyyy/mm/dd hh24:mi:ss') START_TIME, 
-- TO_CHAR(LAST_UPDATE_TIME,'yyyy/mm/dd hh24:mi:ss') LAST_UPDATE_TIME, 
MESSAGE,  
ROUND(SOFAR/TOTALWORK*100,2) "COMPLETE(%)", 
TIME_REMAINING from V$SESSION_LONGOPS 
WHERE OPNAME LIKE 'RMAN%' 
AND OPNAME NOT LIKE '%aggregate%' 
AND TOTALWORK != 0 
AND TIME_REMAINING NOT LIKE '0'
ORDER BY START_TIME;
