set echo off
set lines 200
col TYPE for a10
col START_TIME for a20
col END_TIME for a15
col STATUS for a20
col "INPUT MByte" for 999,999,999
col "OUTPUT MByte" for 999,999,999
col "OUT BYTE/s" for a10
col "TIME_TAKEN" for a10
SELECT rownum NUM#,
  DB_NAME,
  INPUT_TYPE "TYPE",
  TO_CHAR(START_TIME,'yyyy-mm-dd hh24:mi:ss') START_TIME ,
  TO_CHAR(END_TIME,'mm-dd hh24:mi:ss') END_TIME ,
  STATUS,
  TRUNC(INPUT_BYTES /1024/1024) "INPUT MByte" ,
  TRUNC(OUTPUT_BYTES/1024/1024) "OUTPUT MByte",
  OUTPUT_BYTES_PER_SEC_DISPLAY "OUT BYTE/s", 
  TIME_TAKEN_DISPLAY "TIME_TAKEN"
FROM RC_RMAN_BACKUP_JOB_DETAILS
WHERE INPUT_TYPE IN ('DB INCR','DB FULL','ARCHIVELOG')
AND (DB_NAME,START_TIME) IN
(SELECT DB_NAME,
  MAX(START_TIME) START_TIME
  FROM RC_RMAN_BACKUP_JOB_DETAILS
  WHERE INPUT_TYPE IN ('DB INCR','DB FULL','ARCHIVELOG')
  GROUP BY DB_NAME )
ORDER BY rownum, START_TIME;
